//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessCenterIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendances
    {
        public int AttendanceID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<int> SaleID { get; set; }
        public Nullable<System.DateTime> EntryDateTime { get; set; }
        public Nullable<System.DateTime> ExitDateTime { get; set; }
        public string Note { get; set; }
        public Nullable<int> LockerID { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Lockers Lockers { get; set; }
        public virtual Sales Sales { get; set; }
        public virtual Staffs Staffs { get; set; }
        public virtual Staffs Staffs1 { get; set; }
    }
}
