//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessCenterIS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDFitnessClubDipEntities : DbContext
    {
        public BDFitnessClubDipEntities()
            : base("name=BDFitnessClubDipEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attendances> Attendances { get; set; }
        public virtual DbSet<Classifications> Classifications { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<GroupMembers> GroupMembers { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<Guardianships> Guardianships { get; set; }
        public virtual DbSet<LockerRoomTypes> LockerRoomTypes { get; set; }
        public virtual DbSet<Lockers> Lockers { get; set; }
        public virtual DbSet<LoyaltyLevels> LoyaltyLevels { get; set; }
        public virtual DbSet<NumberTrainings> NumberTrainings { get; set; }
        public virtual DbSet<PaymentMethods> PaymentMethods { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<Persons> Persons { get; set; }
        public virtual DbSet<Relationships> Relationships { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Rooms> Rooms { get; set; }
        public virtual DbSet<Sales> Sales { get; set; }
        public virtual DbSet<Schedules> Schedules { get; set; }
        public virtual DbSet<SeasonticketClients> SeasonticketClients { get; set; }
        public virtual DbSet<Seasontickets> Seasontickets { get; set; }
        public virtual DbSet<SeasonticketSales> SeasonticketSales { get; set; }
        public virtual DbSet<SeasonticketServices> SeasonticketServices { get; set; }
        public virtual DbSet<SeasonticketsFreezes> SeasonticketsFreezes { get; set; }
        public virtual DbSet<ServiceClassifications> ServiceClassifications { get; set; }
        public virtual DbSet<ServiceNumberClassTypes> ServiceNumberClassTypes { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<ServiceTrainer> ServiceTrainer { get; set; }
        public virtual DbSet<ServiceTypes> ServiceTypes { get; set; }
        public virtual DbSet<Staffs> Staffs { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TaskPriorities> TaskPriorities { get; set; }
        public virtual DbSet<Tasks> Tasks { get; set; }
        public virtual DbSet<TaskStatuses> TaskStatuses { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Vatrates> Vatrates { get; set; }
        public virtual DbSet<WaitingListClients> WaitingListClients { get; set; }
        public virtual DbSet<WaitingLists> WaitingLists { get; set; }
    }
}
