//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessCenterIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupMembers
    {
        public int GroupMemberID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<int> SeasonticketServiceID { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string Notes { get; set; }
    
        public virtual Groups Groups { get; set; }
        public virtual SeasonticketServices SeasonticketServices { get; set; }
    }
}
