//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessCenterIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guardianships
    {
        public int GuardianshipID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> ResponsiblePersonID { get; set; }
        public Nullable<int> RelationshipID { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Persons Persons { get; set; }
        public virtual Relationships Relationships { get; set; }
    }
}
