//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessCenterIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lockers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lockers()
        {
            this.Attendances = new HashSet<Attendances>();
        }
    
        public int LockerID { get; set; }
        public Nullable<int> LockerRoomTypeID { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
        public string KeyNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendances> Attendances { get; set; }
        public virtual LockerRoomTypes LockerRoomTypes { get; set; }
    }
}
