//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessCenterIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int PaymentID { get; set; }
        public Nullable<int> SaleID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> PaymentMethodID { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
    
        public virtual PaymentMethods PaymentMethods { get; set; }
        public virtual Sales Sales { get; set; }
    }
}
