//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessCenterIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sales()
        {
            this.Attendances = new HashSet<Attendances>();
            this.Payments = new HashSet<Payments>();
            this.SeasonticketSales = new HashSet<SeasonticketSales>();
            this.SeasonticketsFreezes = new HashSet<SeasonticketsFreezes>();
        }
    
        public int SaleID { get; set; }
        public Nullable<int> AdministratorID { get; set; }
        public Nullable<int> TrainerID { get; set; }
        public Nullable<int> SeasonticketID { get; set; }
        public Nullable<int> SeasonticketServiceID { get; set; }
        public Nullable<System.DateTime> SaleDateTime { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> PriceSold { get; set; }
        public Nullable<int> RemainingVisits { get; set; }
        public string StatusSale { get; set; }
        public Nullable<int> VatRateID { get; set; }
        public Nullable<int> ClassificationID { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendances> Attendances { get; set; }
        public virtual Classifications Classifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payments> Payments { get; set; }
        public virtual Seasontickets Seasontickets { get; set; }
        public virtual SeasonticketServices SeasonticketServices { get; set; }
        public virtual Staffs Staffs { get; set; }
        public virtual Users Users { get; set; }
        public virtual Vatrates Vatrates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeasonticketSales> SeasonticketSales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeasonticketsFreezes> SeasonticketsFreezes { get; set; }
    }
}
