//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessCenterIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedules
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Schedules()
        {
            this.WaitingLists = new HashSet<WaitingLists>();
        }
    
        public int ScheduleID { get; set; }
        public string Title { get; set; }
        public Nullable<int> SeasonticketServiceID { get; set; }
        public Nullable<int> TrainerID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public string Note { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string ScheduleStatus { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Groups Groups { get; set; }
        public virtual Rooms Rooms { get; set; }
        public virtual SeasonticketServices SeasonticketServices { get; set; }
        public virtual Staffs Staffs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WaitingLists> WaitingLists { get; set; }
    }
}
