//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessCenterIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeasonticketSales
    {
        public int SeasonticketSaleID { get; set; }
        public Nullable<int> SaleID { get; set; }
        public Nullable<int> SeasonticketID { get; set; }
    
        public virtual Sales Sales { get; set; }
        public virtual Seasontickets Seasontickets { get; set; }
    }
}
