//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessCenterIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeasonticketServices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SeasonticketServices()
        {
            this.GroupMembers = new HashSet<GroupMembers>();
            this.Sales = new HashSet<Sales>();
            this.Schedules = new HashSet<Schedules>();
            this.WaitingLists = new HashSet<WaitingLists>();
        }
    
        public int SeasonticketServiceID { get; set; }
        public Nullable<int> SeasonticketID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<bool> AccessAllowed { get; set; }
        public Nullable<int> SaleID { get; set; }
        public Nullable<int> ServiceNumberClassTypeID { get; set; }
        public Nullable<int> VisitLimit { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupMembers> GroupMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales> Sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedules> Schedules { get; set; }
        public virtual Seasontickets Seasontickets { get; set; }
        public virtual ServiceNumberClassTypes ServiceNumberClassTypes { get; set; }
        public virtual Services Services { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WaitingLists> WaitingLists { get; set; }
    }
}
