//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessCenterIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeasonticketsFreezes
    {
        public int SeasonticketsFreezes1 { get; set; }
        public int SaleID { get; set; }
        public Nullable<int> AdministratorID { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public Nullable<bool> FreezeStatus { get; set; }
        public string Notes { get; set; }
        public Nullable<int> SeasonticketID { get; set; }
    
        public virtual Sales Sales { get; set; }
        public virtual Seasontickets Seasontickets { get; set; }
        public virtual Users Users { get; set; }
    }
}
