//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessCenterIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Services()
        {
            this.Groups = new HashSet<Groups>();
            this.SeasonticketServices = new HashSet<SeasonticketServices>();
            this.ServiceNumberClassTypes = new HashSet<ServiceNumberClassTypes>();
            this.ServiceTrainer = new HashSet<ServiceTrainer>();
        }
    
        public int ServiceID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> ServiceClassificationID { get; set; }
        public Nullable<int> SeviceTypeID { get; set; }
        public string Description { get; set; }
        public Nullable<bool> TrialService { get; set; }
        public Nullable<int> MinAge { get; set; }
        public Nullable<int> Capacity { get; set; }
        public Nullable<decimal> BonusQuantity { get; set; }
        public Nullable<bool> IsFreezable { get; set; }
        public Nullable<int> FreezeDaysLimit { get; set; }
        public string StatusService { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Groups> Groups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeasonticketServices> SeasonticketServices { get; set; }
        public virtual ServiceClassifications ServiceClassifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceNumberClassTypes> ServiceNumberClassTypes { get; set; }
        public virtual ServiceTypes ServiceTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceTrainer> ServiceTrainer { get; set; }
    }
}
