//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessCenterIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceNumberClassTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceNumberClassTypes()
        {
            this.SeasonticketServices = new HashSet<SeasonticketServices>();
        }
    
        public int ServiceNumberClassTypeID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<int> NumberTrainingID { get; set; }
    
        public virtual NumberTrainings NumberTrainings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeasonticketServices> SeasonticketServices { get; set; }
        public virtual Services Services { get; set; }
    }
}
