//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessCenterIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public int TaskID { get; set; }
        public Nullable<int> TaskPrioritieID { get; set; }
        public Nullable<int> TaskStatusID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> AdministratorID { get; set; }
        public Nullable<int> ResponsibleAdministratorID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<System.DateTime> StartDedlainDateTime { get; set; }
        public Nullable<System.DateTime> EndDedlainDateTime { get; set; }
        public string Notes { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual TaskPriorities TaskPriorities { get; set; }
        public virtual TaskStatuses TaskStatuses { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
