//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessCenterIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaitingLists
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WaitingLists()
        {
            this.WaitingListClients = new HashSet<WaitingListClients>();
        }
    
        public int WaitingListID { get; set; }
        public Nullable<int> SheduleID { get; set; }
        public Nullable<int> SeasonticketServiceID { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<bool> IsActivite { get; set; }
    
        public virtual Schedules Schedules { get; set; }
        public virtual SeasonticketServices SeasonticketServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WaitingListClients> WaitingListClients { get; set; }
    }
}
