//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessCenterIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaitingListClients
    {
        public int WaitingID { get; set; }
        public Nullable<int> WaitingListID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<System.DateTime> EnrollmentDateTime { get; set; }
        public Nullable<bool> IsProcessed { get; set; }
        public string Notes { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual WaitingLists WaitingLists { get; set; }
    }
}
